import { NextRequest, NextResponse } from "next/server";
import { ensureSheetHeaders, bulkInsertProperties, getAllProperties, SheetProperty } from "@/lib/sheets";
import { verifyAdminToken, getTokenFromRequest } from "@/lib/auth";

// The existing property data to seed
const SEED_DATA: SheetProperty[] = [
  {
    id: "oakville-green-estate",
    title: "Oakville Green Estate",
    price: "₦4,500,000",
    priceRaw: 4500000,
    location: "Mowe-Ofada, Ogun State",
    state: "Ogun State",
    shortDesc: "Affordable land investment in a fast-developing residential area.",
    fullDesc: "Oakville Green Estate is a residential land development located in Mowe-Ofada, Ogun State. It offers strong investment potential in a rapidly developing area with growing infrastructure and future appreciation value.",
    type: "land", status: "for-sale",
    area: "300, 500 sqm",
    features: ["Electricity","Street lights","Advanced security systems","Perimeter fencing"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1777471180/OK2_i1t9c0.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1777471179/OK1_fbimfq.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1777471177/OK3_glcmbp.jpg",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "cityview-gousa",
    title: "Cityview Park & Resort",
    price: "₦9,000,000",
    priceRaw: 9000000,
    location: "Gousa District, Abuja",
    state: "Abuja",
    shortDesc: "Premium estate land in a developing Abuja district.",
    fullDesc: "City View Park & Resort is a luxurious and serene residential estate located in the Gousa District of Abuja. It offers residents a peaceful escape from the hustle and bustle of city life while still providing easy access to major amenities and attractions.",
    type: "land", status: "for-sale",
    area: "200sqm - Acres",
    features: ["Street Light","Security","Golf club","Helipad","Mini Polo Course","Mini Golf course","Electricity","Electric Car charger port","Recreational Facilities","Artificial intelligence Hub","Drainage"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780321892/gousa1_nrhftq.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1770414061/cityview-gousa_dsucdx.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780321887/hotel_a6sdip.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780321885/gousamap_tz14wx.jpg",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "marbella-estate",
    title: "The Marbella Luxury & Smart Estate",
    price: "₦86,500,000",
    priceRaw: 86500000,
    location: "Lekki-Epe Expressway, Lagos",
    state: "Lagos",
    shortDesc: "Luxury estate land in a prime Lagos investment corridor.",
    fullDesc: "The Marbella Luxury & Smart Estate offers an exceptional living experience in a quiet and serene community. Nestled along the Lekki-Epe Expressway, this estate provides residents with modern, luxurious amenities in a peaceful environment. The land is free from any known encumbrances and adverse ownership.",
    type: "land", status: "for-sale",
    area: "300sqm - 1000sqm",
    features: ["Electricity","Perimeter Fencing","Motorable & Accessible Roads","Shopping Mall","Drainage System"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1770416614/mar2_offxux.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780325447/mar2_ioetcs.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780325446/mar9_ifkb0k.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780325446/mar12_oqnzog.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780325445/mar8_en3kjo.jpg",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "de-avocado-estate",
    title: "De Avocado Smart & Luxury Apartment Estate",
    price: "₦70,000,000",
    priceRaw: 70000000,
    location: "Abijo GRA, Lagos",
    state: "Lagos",
    shortDesc: "Modern smart apartment estate in a gated community.",
    fullDesc: "De Avocado Estate is located at Abijo G.R.A. Inside the prestigious Chois Garden Estate Abijo. Estate Neighborhood includes: Abijo G.R.A., Corona International School, Novare Mall Shoprite, Lagos Business School, Lufasi Nature Park.",
    type: "apartment", status: "for-sale",
    bedrooms: "1,2,3",
    yearBuilt: "2022",
    features: ["Street lights","Electricity","Perimeter Fencing","Motorable & Accessible Roads","Recreational centre","Green Area","Safe and Secured","Estate Gate House","Water Treatment Plant","Mini Football Pitch"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806490/LCRNG%20IMAGES/DeLuxury_htjdvb.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806543/LCRNG%20IMAGES/de2_elgn2r.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806534/LCRNG%20IMAGES/de5_vgbk29.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806487/LCRNG%20IMAGES/de4_olmvbx.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806939/LCRNG%20IMAGES/de6_enneml.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "de-avocado-prime",
    title: "De Avocado Prime",
    price: "COMING SOON",
    priceRaw: 0,
    location: "Alahun, Lekki-Epe Expressway",
    state: "Lagos",
    shortDesc: "Upcoming luxury residential estate development.",
    fullDesc: "De Avocado Prime project promises to elevate the standards of luxury living. It is uniquely designed with exclusive amenities to enhance everyday living. We are committed to delivering quality smart homes in a serene environment along the Lekki–Epe Expressway, very close to the proposed International Airport.",
    type: "house", status: "for-sale",
    features: [],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1770414322/prime7_qqqwhs.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780327730/prime6_rwtmcm.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780327617/prime8_bwhgta.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780327607/prime1_pi77lv.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "queens-garden-annex-isheri",
    title: "Queens Garden Annex",
    price: "₦180,000,000",
    priceRaw: 180000000,
    location: "Isheri-North G.R.A, Lagos",
    state: "Lagos",
    shortDesc: "Luxury homes in a secure gated estate.",
    fullDesc: "Queens Garden Annex offers premium residential homes in a well-secured gated community in Isheri-North GRA with modern designs and serene living. Estate Neighborhood includes: Channels Television H.Q., Lasena Water, F.A.A.N. Estate.",
    type: "house", status: "for-sale",
    bedrooms: "3",
    features: ["Recreational centre","Safe and Secured","Green Area","Water Treatment Plant","Mini Football Pitch","Motorable & Accessible Roads"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806496/LCRNG%20IMAGES/DianaPearl_xs2onv.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806732/LCRNG%20IMAGES/Qu2_jvmdrm.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806761/LCRNG%20IMAGES/Qu1_cgemxn.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806745/LCRNG%20IMAGES/Qu4_ei7820.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806735/LCRNG%20IMAGES/Qu5_rh6kjp.png",
    ],
    featured: false,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "queen-homes-mowe",
    title: "Queen's Home",
    price: "₦47,000,000",
    priceRaw: 47000000,
    location: "Mowe-Ofada, Ogun State",
    state: "Ogun State",
    shortDesc: "Affordable modern residential homes in a growing area.",
    fullDesc: "Queen's Home offers modern residential housing in Mowe-Ofada, a fast-developing area with improving infrastructure and peaceful living environment. Close to International Breweries and Royal Garden City. Nearby landmarks include Nestle Foods Plc and Chrisland Millennium University.",
    type: "house", status: "for-sale",
    bedrooms: "2,3",
    features: ["Recreational centre","Safe and Secured","Green Area","Water Treatment Plant","Mini Football Pitch","Motorable & Accessible Roads"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1770414894/Mowe_kjwpgw.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780329653/mowe5_nlheq0.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780329653/mowehero_r2kwrv.jpg",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "queens-park-estate",
    title: "Queens Park Estate Phase 2",
    price: "₦7,500,000",
    priceRaw: 7500000,
    location: "Mowe-Ofada, Ogun State",
    state: "Ogun State",
    shortDesc: "Affordable land in a fast-developing estate zone.",
    fullDesc: "Queens Park Estate Phase 2 offers residential land in Mowe-Ofada with strong appreciation potential and ongoing development in the area.",
    type: "land", status: "for-sale",
    area: "600 sqm",
    features: ["Recreational centre","Safe and Secured","Green Area","Water Treatment Plant","Mini Football Pitch","Motorable & Accessible Roads"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1770414984/mowe-land_hecz1l.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1780329653/mowe2_qsmrzn.jpg",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806791/LCRNG%20IMAGES/quemoland_kjvj56.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806785/LCRNG%20IMAGES/quemo4_hvmofm.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "panche-villas",
    title: "Panche Villas",
    price: "₦30,000,000",
    priceRaw: 30000000,
    location: "Ilashe, Lagos",
    state: "Lagos",
    shortDesc: "Premium waterfront land in a serene coastal area.",
    fullDesc: "Panche Villas is a luxury land development in Ilashe, Lagos offering waterfront proximity and high-end investment potential. The estate is located on Snake Island off the Lagos coast along Badagry Creek. Estate Neighborhood includes: Inagbe Resort, La Manga Resort, Pop Beach Club, Sencillo Lagos, Jada Beach House, Light House Beach House.",
    type: "land", status: "for-sale",
    area: "500 sqm",
    features: ["Jetty","Electricity","Motorable & Accessible Roads","Green Area","Safe and Secured"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806663/LCRNG%20IMAGES/Panchevillas_jo3reu.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806698/LCRNG%20IMAGES/pan1_xfjlcb.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806652/LCRNG%20IMAGES/pan2_fu4xfx.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806661/LCRNG%20IMAGES/pan4_xkfaqg.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806659/LCRNG%20IMAGES/pan3_dnqbqt.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "suncity-karshi",
    title: "Suncity Green & Smart Estate",
    price: "₦4,000,000",
    priceRaw: 4000000,
    location: "Karshi, Abuja",
    state: "Abuja",
    shortDesc: "Affordable smart estate land in Abuja outskirts.",
    fullDesc: "SunCity Green and Smart Estate is located in a vibrant and growing community in Karshi, Abuja. Estate neighborhood includes Karshi Waterfalls, Ave Maria University, Civil Defence Estate, Naval Estate.",
    type: "land", status: "for-sale",
    area: "300 - 500sqm, Acre",
    features: ["Electricity","Perimeter Fencing","Motorable & Accessible Roads","Shopping Mall","Drainage System"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1770415375/suncity_hu8wq9.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "queens-park-estate-kuje",
    title: "Queens Park Estate Kuje",
    price: "₦4,000,000",
    priceRaw: 4000000,
    location: "Kuje, Abuja",
    state: "Abuja",
    shortDesc: "Affordable land in a growing Abuja district.",
    fullDesc: "Queens Park Estate Kuje offers affordable residential land in Abuja with good road access and development potential.",
    type: "land", status: "for-sale",
    area: "300 - 500sqm",
    features: ["Street lights","Electricity","Perimeter Fencing","Motorable & Accessible Roads","Recreational centre","Green Area","Safe and Secured","Estate Gate House","Water Treatment Plant","Mini Football Pitch"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806755/LCRNG%20IMAGES/queens_kuje_qwhhxt.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806555/LCRNG%20IMAGES/kuj2_ekorcs.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806565/LCRNG%20IMAGES/kuj4_m1vqyp.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806557/LCRNG%20IMAGES/kuj3_sk2gpc.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "queens-park-estate-karshi",
    title: "Queens Park Estate Karshi",
    price: "₦4,000,000",
    priceRaw: 4000000,
    location: "Karshi, Abuja",
    state: "Abuja",
    shortDesc: "Residential land in a developing Abuja suburb.",
    fullDesc: "Queens Park Estate Karshi offers affordable land for residential purposes in a fast-growing area of Abuja.",
    type: "land", status: "for-sale",
    area: "300 - 500sqm",
    features: ["Street lights","Electricity","Perimeter Fencing","Motorable & Accessible Roads","Recreational centre","Green Area","Safe and Secured","Estate Gate House","Water Treatment Plant","Mini Football Pitch"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806760/queens_park1_upsi1v.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806579/LCRNG%20IMAGES/kar2_bv4rtk.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806554/LCRNG%20IMAGES/kar3_quqhyv.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806550/LCRNG%20IMAGES/kar1_mgoyjq.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "fairmont",
    title: "The Fairmont Green & Smart Estate",
    price: "₦18,000,000",
    priceRaw: 18000000,
    location: "Ibeju-Lekki, Lagos",
    state: "Lagos",
    shortDesc: "Smart estate land in a fast-growing Lagos corridor.",
    fullDesc: "The Fairmont Green & Smart Estate offers premium plots in Ibeju-Lekki, designed for modern residential development and strong investment returns.",
    type: "land", status: "for-sale",
    area: "300 - 500sqm",
    features: ["Green Area","Solar Powered","Renewable Energy","Perimeter Fencing","Motorable & Accessible Roads","EV charging port","Mini Football field"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806499/LCRNG%20IMAGES/fairmont_kszzj2.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806507/LCRNG%20IMAGES/far1_kohjx3.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806542/LCRNG%20IMAGES/far2_eiu29v.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806511/LCRNG%20IMAGES/far3_qxur9w.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806548/LCRNG%20IMAGES/far5_sk4s2j.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "queens-garden-annex-centenary-city",
    title: "Queens Garden Annex Centenary City",
    price: "₦6,000,000",
    priceRaw: 6000000,
    location: "Centenary City, Abuja",
    state: "Abuja",
    shortDesc: "Affordable estate land in Centenary City.",
    fullDesc: "Queens Garden Annex is in Abuja, strategically located behind the Centenary City and within proximity of the Nnamdi Azikiwe International Airport. Estate Neighborhood includes: Centenary City, Abuja @ 50, Nigerian Naval Barracks Abuja.",
    type: "land", status: "for-sale",
    area: "300 - 500sqm",
    features: ["Street lights","Electricity","Perimeter Fencing","Motorable & Accessible Roads","Recreational centre","Green Area","Safe and Secured","Estate Gate House","Water Treatment Plant","Mini Football Pitch"],
    images: [
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806755/LCRNG%20IMAGES/queens_Annex_Abuja_i5hklp.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806744/LCRNG%20IMAGES/quece2_xyp75j.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806746/LCRNG%20IMAGES/quece3_o6mtjg.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806749/LCRNG%20IMAGES/quece5_coj5li.png",
      "https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806742/LCRNG%20IMAGES/quece1_c2tsbb.png",
    ],
    featured: true,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "queens-garden-simawa",
    title: "The Queens Garden Estate",
    price: "SALES CLOSED",
    priceRaw: 0,
    location: "Simawa, Ogun State",
    state: "Ogun State",
    shortDesc: "Sold out residential estate project.",
    fullDesc: "The Queens Garden Estate in Simawa is fully sold out and represents a completed residential development project.",
    type: "land", status: "sold",
    features: [],
    images: ["https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806792/LCRNG%20IMAGES/queens_Estate_irqf4y.png"],
    featured: false,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "lakeview",
    title: "Lakeview Park & Resort",
    price: "SALES CLOSED",
    priceRaw: 0,
    location: "Ketu-Epe, Lagos",
    state: "Lagos",
    shortDesc: "Completed and sold out estate project.",
    fullDesc: "Lakeview Park & Resort is a completed estate development in Ketu-Epe, Lagos, now fully sold out.",
    type: "land", status: "sold",
    features: [],
    images: ["https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806584/LCRNG%20IMAGES/LakeviewLand_z0v1be.png"],
    featured: false,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "cityview-gwagwalada",
    title: "Cityview Gwagwalada",
    price: "SALES CLOSED",
    priceRaw: 0,
    location: "Gwagwalada, Abuja",
    state: "Abuja",
    shortDesc: "Sold out estate development in Abuja.",
    fullDesc: "Cityview Park & Resort is located in a vibrant and growing community in Gwagwalada, Abuja. Estate neighborhood includes Abuja Airport, University of Abuja, University of Abuja Teaching Hospital, and WAEC Office.",
    type: "land", status: "sold",
    area: "300sqm, 500sqm, Acres, Hectares",
    features: ["Street Light","Security","Perimeter Fencing","Motorable & Accessible","Electricity","Estate Gate House","Recreational Facilities","Drainage"],
    images: ["https://res.cloudinary.com/dqzsdgugd/image/upload/v1770413689/Gemini_Generated_Image_stuhv4stuhv4stuh_vgpnlh.png"],
    featured: false,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "paragon",
    title: "Paragon Terraces & Duplexes",
    price: "SALES CLOSED",
    priceRaw: 0,
    location: "Abraham Adesanya, Lagos",
    state: "Lagos",
    shortDesc: "Sold out residential duplex project.",
    fullDesc: "Paragon Terraces & Duplexes is a completed residential housing project in Lagos and is fully sold out.",
    type: "house", status: "sold",
    features: [],
    images: ["https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806738/LCRNG%20IMAGES/Paragon_rmesn7.png"],
    featured: false,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "meridian",
    title: "Meridian Boulevard Estate",
    price: "SALES CLOSED",
    priceRaw: 0,
    location: "Okun-Ajah, Ogombo, Lagos",
    state: "Lagos",
    shortDesc: "Sold out premium estate project.",
    fullDesc: "Meridian Boulevard Estate is a completed residential development in Lagos and is fully sold out.",
    type: "land", status: "sold",
    features: [],
    images: ["https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806642/LCRNG%20IMAGES/Meridian_tac1uu.png"],
    featured: false,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
  {
    id: "lagoonfront-estate",
    title: "The Lagoonfront Estate",
    price: "SALES CLOSED",
    priceRaw: 0,
    location: "Eleko, Lagos",
    state: "Lagos",
    shortDesc: "Sold out waterfront estate project.",
    fullDesc: "The Lagoonfront Estate in Eleko, Lagos is a completed waterfront development and is fully sold out.",
    type: "land", status: "sold",
    features: [],
    images: ["https://res.cloudinary.com/dqzsdgugd/image/upload/v1716806591/LCRNG%20IMAGES/Lagoonfront_gdtvqg.png"],
    featured: false,
    agent: { name: "Omotayo Dosunmu", phone: "+2347067882908", whatsapp: "2347067882908" },
  },
];

export async function POST(req: NextRequest) {
  const token = getTokenFromRequest(req);
  if (!token) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const session = await verifyAdminToken(token);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    // 1. Write headers
    await ensureSheetHeaders();

    // 2. Check existing data to avoid duplicates
    let existing: SheetProperty[] = [];
    try { existing = await getAllProperties(); } catch { /* empty sheet */ }

    const existingIds = new Set(existing.map(p => p.id));
    const toInsert = SEED_DATA.filter(p => !existingIds.has(p.id));

    if (toInsert.length === 0) {
      return NextResponse.json({
        success: true,
        message: `All ${SEED_DATA.length} properties already exist in the sheet. Nothing to insert.`,
        inserted: 0,
        skipped: SEED_DATA.length,
      });
    }

    // 3. Bulk insert
    await bulkInsertProperties(toInsert);

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${toInsert.length} properties into Google Sheets.`,
      inserted: toInsert.length,
      skipped: SEED_DATA.length - toInsert.length,
    });
  } catch (err: any) {
    console.error("Seed error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
